module.exports = {
  someSidebar: [
    "preface",
    "introduction",
    "navigation",
    {
      "1. Atomic Structure": [
        "atomic-structure/classroom-language",
        "atomic-structure/language-structure",
        "atomic-structure/vocabulary-practice-tips",
        "atomic-structure/glossary",
        "atomic-structure/reading-the-structure-of-an-atom",
        "atomic-structure/reading-electron-shell-of-an-atom",
        "atomic-structure/reading-mass-spectrometry",
        "atomic-structure/video-lesson",
        "atomic-structure/bloom-taxonomy",
        "atomic-structure/students-self-study",
        "atomic-structure/teaching-method",
      ],
      "2. Periodicity": [
        "periodicity/classroom-language",
        "periodicity/language-structure",
        "periodicity/vocabulary-practice-tips",
        "periodicity/glossary",
        "periodicity/reading-periodicity",
        "periodicity/video-lesson",
        "periodicity/bloom-taxonomy",
        "periodicity/students-self-study",
        "periodicity/teaching-method",
      ],
      "3. Bonding": [
        "bonding/classroom-language",
        "bonding/language-structure",
        "bonding/vocabulary-practice-tips",
        "bonding/glossary",
        "bonding/reading-bonding",
        "bonding/video-lesson",
        "bonding/bloom-taxonomy",
        "bonding/students-self-study",
        "bonding/teaching-method",
      ],
      "4. Energetics": [
        "energetics/classroom-language",
        "energetics/language-structure",
        "energetics/vocabulary-practice-tips",
        "energetics/glossary",
        "energetics/reading-the-enthalpy-changes",
        "energetics/video-lesson",
        "energetics/bloom-taxonomy",
        "energetics/students-self-study",
        "energetics/teaching-method",
      ],
      "5. Kinetics": [
        "kinetics/classroom-language",
        "kinetics/language-structure",
        "kinetics/vocabulary-practice-tips",
        "kinetics/glossary",
        "kinetics/reading-the-rate-of-reaction",
        "kinetics/video-lesson",
        "kinetics/bloom-taxonomy",
        "kinetics/students-self-study",
        "kinetics/teaching-method",
      ],
      "6. Equilibrium": [
        "equilibrium/classroom-language",
        "equilibrium/language-structure",
        "equilibrium/vocabulary-practice-tips",
        "equilibrium/glossary",
        "equilibrium/reading-equilibrium",
        "equilibrium/video-lesson",
        "equilibrium/bloom-taxonomy",
        "equilibrium/students-self-study",
        "equilibrium/teaching-method",
      ],
      "7. Alkanes": [
        "alkanes/classroom-language",
        "alkanes/language-structure",
        "alkanes/vocabulary-practice-tips",
        "alkanes/glossary",
        "alkanes/reading-alkanes",
        "alkanes/reading-hydrocarbons",
        "alkanes/video-lesson",
        "alkanes/bloom-taxonomy",
        "alkanes/students-self-study",
        "alkanes/teaching-method",
      ],
      "8. Alkenes": [
        "alkenes/classroom-language",
        "alkenes/language-structure",
        "alkenes/vocabulary-practice-tips",
        "alkenes/glossary",
        "alkenes/reading-alkenes",
        "alkenes/video-lesson",
        "alkenes/bloom-taxonomy",
        "alkenes/students-self-study",
        "alkenes/teaching-method",
      ],
      "9. Alcohols": [
        "alcohols/classroom-language",
        "alcohols/language-structure",
        "alcohols/vocabulary-practice-tips",
        "alcohols/glossary",
        "alcohols/reading-alcohols",
        "alcohols/video-lesson",
        "alcohols/bloom-taxonomy",
        "alcohols/students-self-study",
        "alcohols/teaching-method",
      ],
      "10. Halogenoalkanes": [
        "halogenoalkanes/classroom-language",
        "halogenoalkanes/language-structure",
        "halogenoalkanes/vocabulary-practice-tips",
        "halogenoalkanes/glossary",
        "halogenoalkanes/reading-halogenoalkanes",
        "halogenoalkanes/video-lesson",
        "halogenoalkanes/bloom-taxonomy",
        "halogenoalkanes/students-self-study",
        "halogenoalkanes/teaching-method",
      ],
      "11. Analytical techniques": [
        "analytical-techniques/classroom-language",
        "analytical-techniques/language-structure",
        "analytical-techniques/vocabulary-practice-tips",
        "analytical-techniques/glossary",
        "analytical-techniques/reading-chromatography",
        "analytical-techniques/reading-mass-spectrometry",
        "analytical-techniques/reading-infrared-spectroscopy",
        "analytical-techniques/reading-NMR-spectroscopy",
        "analytical-techniques/video-lesson",
        "analytical-techniques/bloom-taxonomy",
        "analytical-techniques/students-self-study",
        "analytical-techniques/teaching-method",
      ],
      "12. The redox reactions": [
        "the-redox-reactions/classroom-language",
        "the-redox-reactions/language-structure",
        "the-redox-reactions/vocabulary-practice-tips",
        "the-redox-reactions/glossary",
        "the-redox-reactions/reading-redox-reaction",
        "the-redox-reactions/video-lesson",
        "the-redox-reactions/bloom-taxonomy",
        "the-redox-reactions/students-self-study",
        "the-redox-reactions/teaching-method",
      ],
      "13. Halogens": [
        "halogens/classroom-language",
        "halogens/language-structure",
        "halogens/vocabulary-practice-tips",
        "halogens/glossary",
        "halogens/reading-halogens",
        "halogens/video-lesson",
        "halogens/bloom-taxonomy",
        "halogens/students-self-study",
        "halogens/teaching-method",
      ],
      "14. The alkaline earth elements": [
        "alkaline-earth-elements/classroom-language",
        "alkaline-earth-elements/language-structure",
        "alkaline-earth-elements/vocabulary-practice-tips",
        "alkaline-earth-elements/glossary",
        "alkaline-earth-elements/reading-alkaline-earth-elements",
        "alkaline-earth-elements/video-lesson",
        "alkaline-earth-elements/bloom-taxonomy",
        "alkaline-earth-elements/students-self-study",
        "alkaline-earth-elements/teaching-method",
      ],
      "15. Thermodynamics": [
        "thermodynamics/classroom-language",
        "thermodynamics/language-structure",
        "thermodynamics/vocabulary-practice-tips",
        "thermodynamics/glossary",
        "thermodynamics/reading-thermodynamics",
        "thermodynamics/video-lesson",
        "thermodynamics/bloom-taxonomy",
        "thermodynamics/students-self-study",
        "thermodynamics/teaching-method",
      ],
      "16. Chemical calculations": [
        "сhemical-calculations/language-structure",
        "сhemical-calculations/practice-exercises",
        "сhemical-calculations/video-lesson",
        "сhemical-calculations/students-self-study",
        "сhemical-calculations/teaching-method",
      ],
      Appendix: [
        "appendix/1",
        "appendix/2",
        "appendix/3",
        "appendix/4",
        "appendix/5",
      ],
    },
    "credentials",
  ],
};
